### PR TITLE
autovpn.go: Same great functionality, much less indentation-y taste

### PR DESCRIPTION
**Pull request by elimisteve**

### CODE REVIEW

**Comment by elimisteve** [comment]
I found you on reddit :-). This seems to work for me on Ubuntu, btw. Nice!

**Comment by adtac** [comment]
Thanks! I used a tool to do the formatting, somehow messed up :D 

Glad to know it works on Ubuntu too. I'll add that to the README soon.

**Comment by elimisteve** [comment]
@adtac Look carefully at the new source :-). It's not identical but with less indenting, I just tweaked things to do things in a more Go-ish way, where if there's a problem, you return/exit/continue/break rather than saying "if there _isn't_ a problem, indent another level and keep going". Make sense?

**Comment by adtac** [comment]
Yeah, that's probably better. This was mostly a excercise for me to learn Go. I'm trying to do things in Go that I'd normally do with Python :)

**Pull request merged**
